CREATE TABLE mytable(
   id              INTEGER  NOT NULL PRIMARY KEY 
  ,kategori        VARCHAR(8) NOT NULL
  ,nama            VARCHAR(28) NOT NULL
  ,deskripsi       VARCHAR(287) NOT NULL
  ,harga           VARCHAR(10) NOT NULL
  ,berat           VARCHAR(7) NOT NULL
  ,gambar          VARCHAR(6) NOT NULL
  ,stok            INTEGER  NOT NULL
  ,produk0ukuran   VARCHAR(49) NOT NULL
  ,produk0warna    VARCHAR(61) NOT NULL
  ,produk0bahan    VARCHAR(36) NOT NULL
  ,produk0tipe     VARCHAR(8) NOT NULL
);
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (1,'laptop','ASUS TUF Gaming FX505','Laptop ini dibekali dengan spesifikasi terbaik yang dapat menunjang performa tinggi tanpa kendala sama sekali.','15.900.000','2.3 kg','1.jpg',1,'15.6 inch','black','alumunium','gaming');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (2,'laptop','Acer Chromebook 514','Bodi laptop premium ini masih mempertahankan material aluminium sebagai pelapis bodi utama.','3.800.000','1.3 Kg','2.jpg',10,'14 inch','white','aluminium','notebook');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (3,'laptop','Toshiba Portege X20W','Toshiba Portege X20W hadir dengan prosesor Intel Core i7-7500U untuk mendukung performa tinggi agar tetap stabil.','7.000.000','1.1 kg','3.jpg',9,'299 x 219 x 15.4mm','white, black','magnesium untuk chassis','notebook');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (4,'laptop','Xiaomi Mi Notebook Air','Merk laptop terbaik asal pabrikan Cina ini hadir dalam dua pilihan, yaitu layar 12,5 inci dan layar 13,3 inci.','5.590.000','5.7 Kg','4.jpg',5,'13.3 inch','white','besi dan perbaduan warna futuristik','notebook');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (5,'laptop','Lenovo Ideapad Gaming 3 N1ID','Body perangkat ini terlihat polos di bagian belakang, namun dengan kontur body yang sedikit terlihat polygonal di beberapa sudut. Pada bagian pinggi body terdapat logo Lenovo yang diukir pada lempengan logam, menjadi ciri khas laptop Lenovo seri Ideapad.','12.300.000','2.08 Kg','5.jpg',4,'panjang 35,9 cm, Lebar 24,9 cm, dan tebal 2,49 cm','Onyx Black','plastik','gaming');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (6,'laptop','Acer Nitro 5 Gaming','Acer Nitro 5 adalah laptop dengan layar 15.6 dan resolusi 1920 x 1080pixels yang dilengkapi spesifikasi mumpuni. Laptop dengan berat 2.48kg ini ditenagai kartu grafis NVIDIA® GeForce RTX™ 3060 dan didukung sistem operasi Windows 10 Home.','11.775.489','2,17 Kg','6.jpg',2,'panjang 36,3 cm, lebar 25,4cm, dan tebal 2,3 cm','Black','plastik','gaming');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (7,'laptop','Macbook Apple 2018','MacBook Pro 2018 varian 13 inch dirilis dengan menghadirkan prosesor Intel Quad-Core generasi ke-8 yang punya performa 2x lebih tinggi dibandingkan generasi sebelumnya.','15.880.000','1.37 Kg','7.jpg',5,'13.3 inch','silver','alumunium','macbook');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (8,'laptop','Lenovo IdeaPad Slim 3','Lenovo IdeaPad Slim 3 hadir dengan dukungan prosesor AMD Ryzen 5 4500U dengan Radeon Graphics 2,38 GHz, serta RAM 8GB dan ruang penyimpanan internal SSD berkapasitas 512GB.','10.799.000','1.6 Kg','8.jpg',10,'14 inch','Platinum Grey, Abyss Blue, Cherry Red, Almond, Business Black','alumunium','notebook');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (9,'laptop','ASUS VivoBook 14 A412FA','Laptop ASUS VivoBook 14 A412FA adalah ultrabook dengan bobot 1.5kg dan layar 14 inch beresolusi 1920 x 1080pixels.','12.920.000','1.5 Kg','9.jpg',10,'14 inch','white','alumunium','notebook');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (10,'laptop','Huawei Matebook 14s','Laptop ASUS VivoBook 14 A412FA adalah ultrabook dengan bobot 1.5kg dan layar 14 inch beresolusi 1920 x 1080pixels.','15.999.000','1.43 Kg','10.jpg',10,'14.2 inch','white','alumunium','notebook');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (11,'earphone','Fantech SCAR EG2','Fantech SCAR EG2 merupakan headset gaming yang dilengkapi dengan mikrofon ganda yang fleksibel, mic bisa dipasang dan dilepas sesuai keperluan.','130.000','300 g','11.jpg',10,'15 mm','white, black','alumunium','earphone');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (12,'earphone','KZ ZS10','Earphone besutan Knowledge Zenith ini mempunyai frekuensi  7Hz-40000Hz, impendasi 32 ohms, dan sensitivitas 104 DB yang performanya memukau dan bassnya sangat terdengar rapi. Selain itu, KZ ZS10 memiliki kabel over-the-ear berbentuk anyaman dan transparan yang bisa dicopot dan dipasang.','389.000','250 g','12.jpg',3,'1.2m±3cm','blue, purple','alumunium','wireless');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (13,'earphone','Pioneer Extra Bass SE-QL2T','Headset In Ear Monitor (IEM) ini berbahan dasar aluminium yang mampu menahan getaran yang mengganggu kualitas suara dibandingkan plastik. Desain yang dimiliki juga cukup elegan. Dengan konsep kepala earbud yang miring beberapa derajat, headset ini nyaman saat dipakai.','299.000','200 g','13.jpg',5,'15 mm','red, black','alumunium','earphone');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (14,'earphone','Sony MDR-XB55AP','Kualitas semakin memukau dengan Powered Bass Duct++ yang memberikan bass yang bertenaga dan enak didengar. Dengan lima pilihan warna yang menarik, kamu bisa memilih warna earphone favoritmu untuk tampil gaya dengan earphone berkualitas.','399.000','300 g','14.jpg',6,'12 mm','red','alumunium','earphone');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (15,'earphone','Sennheiser CX 1.00','Sennheiser CX 1.00 memiliki keunggulan suara yang jernih di hampir seluruh rentang frekuensi 17 to 20,000 Hz saat mendengarkan lagu.','571.000','500 g','15.jpg',6,'1.2m','black','alumunium','earphone');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (16,'earphone','PHILIPS SHE3015','PHILIPS SHE3015 merupakan salah satu pilihan product earphone terbaik keluaran Philips. Disempurnakan dengan bass yang kuat serta ear ban lembut yang nyaman, tipe headset populer ini juga memiliki desain yang trendy.','200.000','125 g','16.jpg',6,'15 mm','black','neodymium','earphone');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (17,'earphone','Hoco M55 Earphone','Hoco M55 Earphone adalah headset in ear yang hadir dalam berbagai pilihan warna. Kamu akan dimanjakan dengan suara berkualitas tinggi untuk menemani kamu beraktivitas.','129.472','125 g','17.jpg',6,'15 mm','white','plastik','earphone');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (18,'earphone','Apple AirPods','Apple AirPods adalah headset Bluetooth yang dapat digunakan selama 3h waktu bicara dan 5h waktu beroperasi.','1.323.000','4 g','18.jpg',6,'15 mm','white','plastik','earphone');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (19,'earphone','JBL Everest 110','JBL Everest 110 adalah headset in ear yang hadir dalam berbagai pilihan warna. Kamu akan dimanjakan dengan suara berkualitas tinggi untuk menemani kamu beraktivitas.','720.000','15 g','19.jpg',6,'15 mm','white','plastik','earphone');
INSERT INTO mytable(id,kategori,nama,deskripsi,harga,berat,gambar,stok,produk0ukuran,produk0warna,produk0bahan,produk0tipe) VALUES (20,'earphone','Remax RM 303','Remax RM 303 adalah headset in ear yang hadir dalam berbagai pilihan warna. Kamu akan dimanjakan dengan suara berkualitas tinggi untuk menemani kamu beraktivitas.','78.000','15 g','20.jpg',6,'15 mm','black','plastik','earphone');
